
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/bionic64"

  
  config.vm.hostname = "mi-servidor-local"


  config.vm.network "private_network", ip: "192.168.56.10"


  config.vm.synced_folder "../", "/var/www/html"

  
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    a2enmod rewrite
    systemctl restart apache2
  SHELL
end
